version: '3.8'

services:
  order-solution:
    image: 'ostapenko/order-solution:latest'
    build:
      context: .
    container_name: order-solution
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=order-solution
      - POSTGRES_PASSWORD=order-solution
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order-solution
      - SPRING_DATASOURCE_USERNAME=order-solution
      - SPRING_DATASOURCE_PASSWORD=order-solution
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "6868:8080"

  postgres:
    image: 'bitnami/postgresql:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=order-solution
      - POSTGRES_PASSWORD=order-solution
      - POSTGRES_DB=order-solution
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"